import type { JobApplication } from "@/components/dashboard/types";

export const seedApps: JobApplication[] = [
  {
    id: "1",
    company: "Acme Corp",
    role: "Software Engineer Intern",
    location: "New York, NY",
    url: "https://example.com/job/1",
    status: "Applied",
    priority: "High",
    salary: "$85,000",
    appliedDate: "2026-02-01",
    notes: "Submitted via portal",
  },
  {
    id: "2",
    company: "Globex",
    role: "Frontend Developer",
    location: "Remote",
    url: "https://example.com/job/2",
    status: "Interview",
    priority: "High",
    salary: "$110,000",
    appliedDate: "2026-02-03",
    notes: "Recruiter screen scheduled",
  },
  {
    id: "3",
    company: "Initech",
    role: "Full Stack Engineer",
    location: "Austin, TX",
    url: "https://example.com/job/3",
    status: "Applied",
    priority: "Medium",
    salary: "$130,000",
    appliedDate: "2026-02-10",
    notes: "",
  },
  {
    id: "4",
    company: "Umbrella Corp",
    role: "Backend Engineer",
    location: "San Francisco, CA",
    url: "",
    status: "Rejected",
    priority: "Low",
    salary: "$95,000",
    appliedDate: "2026-01-20",
    notes: "No feedback given",
  },
  {
    id: "5",
    company: "Stark Industries",
    role: "React Developer",
    location: "Remote",
    url: "https://example.com/job/5",
    status: "Wishlist",
    priority: "Medium",
    salary: "$140,000",
    appliedDate: "",
    notes: "Apply next month",
  },
];